---
- name: CentOS/RedHat | Include distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - 'default.yml'

- name: Debian/Ubuntu | Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Debian/Ubuntu | Add hashicorp key
  ansible.builtin.get_url:
    url: "{{ repository_hashicorp_key_url }}"
    dest: "{{ repository_hashicorp_keyring }}"
    mode: "0644"
    force: false
  when:
    - ansible_facts['os_family'] == "Debian"

- name: Debian/Ubuntu | Add hashicorp repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ repository_hashicorp_keyring }}] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    state: present
    filename: hashicorp
  register: repository_hashicorp_status
  when:
    - ansible_facts['os_family'] == "Debian"

- name: CentOS/RedHat | Add hashicorp repository
  ansible.builtin.get_url:
    url: "{{ hashicorp_repository_url[ansible_facts['distribution']] }}"
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: "0644"
  register: repository_hashicorp_status
  until: repository_hashicorp_status is succeeded
  retries: 5
  delay: 10
  when:
    - ansible_facts["distribution"] in [ "RedHat", "CentOS", "Amazon", "Rocky", "AlmaLinux", "Fedora" ]
