---
- name: CentOS/RedHat | Include distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - 'default.yml'

- name: Debian/Ubuntu | Add hashicorp key
  ansible.builtin.apt_key:
    url: "{{ repository_hashicorp_key_url }}"
    state: present
    validate_certs: false
  when:
    - ansible_os_family == "Debian"

- name: Debian/Ubuntu | Add hashicorp repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp
  register: repository_hashicorp_status
  when:
    - ansible_os_family == "Debian"

- name: CentOS/RedHat | Add hashicorp repository
  ansible.builtin.get_url:
    url: "{{ hashicorp_repository_url[ansible_distribution] }}"
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: "0644"
  register: repository_hashicorp_status
  until: repository_hashicorp_status is succeeded
  retries: 5
  delay: 10
  when:
    - ansible_distribution in [ "RedHat", "CentOS", "Amazon", "Rocky", "AlmaLinux", "Fedora" ]
