---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    molecule_repo_file: "hashicorp"
    molecule_repo_name: "hashicorp"
    molecule_repo_package: "nomad"
    molecule_keyring: "/etc/apt/keyrings/hashicorp.asc"

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_facts['distribution'] }}"
          - "ansible_distribution_major_version => {{ ansible_facts['distribution_major_version'] }}"
          - "ansible_os_family  => {{ ansible_facts['os_family'] }}"
          - "ansible_system  => {{ ansible_facts['system'] }}"

    - name: "APT | Test if keyring file exists"
      ansible.builtin.stat:
        path: "{{ molecule_keyring }}"
      register: molecule_keyring_stat
      failed_when:
        - not molecule_keyring_stat.stat.exists
      when:
        - ansible_facts['os_family'] == "Debian"

    - name: "APT | Test if repository exists"
      ansible.builtin.lineinfile:
        name: '/etc/apt/sources.list.d/{{ molecule_repo_file }}.list'
        line: "deb [signed-by={{ molecule_keyring }}] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
        state: present
      check_mode: true
      register: molecule_repository
      failed_when: (molecule_repository is changed) or (molecule_repository is failed)
      when:
        - ansible_facts['os_family'] == "Debian"

    - name: "YUM | Test if repository exists"
      ansible.builtin.lineinfile:
        name: "/etc/yum.repos.d/{{ molecule_repo_file }}.repo"
        line: "[{{ molecule_repo_name }}]"
        state: present
      check_mode: true
      register: molecule_repository_yum
      failed_when: (molecule_repository_yum is changed) or (molecule_repository_yum is failed)
      when:
        - ansible_facts['distribution'] in [ "RedHat", "CentOS", "Rocky", "AlmaLinux", "Fedora" ]

    - name: Check packages are installable from repository
      ansible.builtin.package:
        name: "{{ molecule_repo_package }}"
        state: present
